export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  image: string;
  category: string;
  inStock: boolean;
  discount?: number;
  description: string;
  features?: string[];
  specs?: Record<string, string>;
}

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Pro Travel Backpack',
    price: 12999,
    originalPrice: 15999,
    rating: 4.8,
    reviews: 324,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
    category: 'Backpacks',
    inStock: true,
    discount: 18,
    description: 'A premium, water-resistant travel backpack designed for digital nomads and weekend explorers. Featuring a 16-inch laptop compartment, hidden security pockets, and ergonomic shoulder straps for maximum comfort during long transits.',
    features: ['Water-resistant Ballistic Nylon', 'Dedicated 16" laptop sleeve', 'Hidden anti-theft pocket', 'USB charging port access', 'Clamshell opening for easy packing'],
    specs: { Capacity: '40 Liters', Weight: '1.2 kg', Material: '1680D Ballistic Nylon', Dimensions: '50 x 32 x 20 cm' }
  },
  {
    id: '2',
    name: 'Durable Travel Luggage',
    price: 24999,
    originalPrice: 29999,
    rating: 4.6,
    reviews: 215,
    image: 'https://images.unsplash.com/photo-1581553680321-4fffae59fccd?w=600&h=600&fit=crop',
    category: 'Luggage',
    inStock: true,
    discount: 16,
    description: 'Ultra-lightweight yet virtually indestructible hardshell suitcase with 360-degree silent spinner wheels. Features TSA-approved lock and compression system to pack 20% more.',
    features: ['Polycarbonate Hardshell', 'TSA-Approved Combination Lock', '360° Silent Double-Spinner Wheels', 'Internal Compression Board', 'Scratch-resistant matte finish'],
    specs: { Capacity: '75 Liters', Weight: '3.4 kg', Material: '100% Polycarbonate', Dimensions: '68 x 45 x 26 cm' }
  },
  {
    id: '3',
    name: 'Premium Camera Bag',
    price: 8999,
    originalPrice: 11999,
    rating: 4.9,
    reviews: 142,
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 25,
    description: 'The ultimate protection for your camera gear. Equipped with customizable padded dividers, weather-proof zippers, and quick side access, this bag makes photography on the go seamless and secure.',
    features: ['Customizable EVA dividers', 'Dual side quick access', 'All-weather rain cover', 'Tripod attachment strap', 'Breathable mesh back panel'],
    specs: { Capacity: '20 Liters', Weight: '0.95 kg', Material: 'Weatherproof Canvas', Dimensions: '45 x 30 x 18 cm' }
  },
  {
    id: '4',
    name: 'Smart Travel Tracker',
    price: 4999,
    originalPrice: 6249,
    rating: 4.7,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
    category: 'Electronics',
    inStock: true,
    discount: 20,
    description: 'Never lose your bags again. This ultra-thin, rechargeable GPS and Bluetooth tracker fits into any wallet or luggage tag, providing real-time location tracking globally via your smartphone.',
    features: ['Global GPS tracking', 'Rechargeable battery (lasts 3 months)', 'Left-Behind alerts', 'Waterproof IP67 rating', 'Built-in ring speaker'],
    specs: { Battery: 'Rechargeable Li-ion', Connectivity: 'Bluetooth 5.2 + GPS', Weight: '28g', Dimensions: '85 x 54 x 2.4 mm' }
  },
  {
    id: '5',
    name: 'Ultra-Light Tent',
    price: 15999,
    originalPrice: 19999,
    rating: 4.8,
    reviews: 276,
    image: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=600&h=600&fit=crop',
    category: 'Camping',
    inStock: true,
    discount: 20,
    description: 'A 2-person double-walled backpacking tent built for extreme durability. Highly windproof and waterproof, yet packs down small enough to fit inside your backpack water bottle pocket.',
    features: ['Double-walled insulation', 'PU 5000mm waterproof coating', 'Aviation-grade aluminum poles', 'Dual entrances & vestibules', 'High-density micro mesh ventilation'],
    specs: { Capacity: '2 Persons', Weight: '1.45 kg', Material: '20D Ripstop Nylon', PackSize: '40 x 12 cm' }
  },
  {
    id: '6',
    name: 'Waterproof Travel Shoes',
    price: 5999,
    originalPrice: 7999,
    rating: 4.6,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    category: 'Shoes',
    inStock: true,
    discount: 25,
    description: 'Engineered for comfort during long city walks or rugged mountain hikes. These shoes are completely waterproof, breathable, and feature slip-resistant rubber soles for excellent grip.',
    features: ['Waterproof breathable membrane', 'Ortholite cushioning insoles', 'All-terrain rubber outsoles', 'Anti-collision rubber toe cap', 'Lace-up quick adjustment'],
    specs: { Weight: '680g (pair)', Upper: 'Mesh + TPU', Outsole: 'Rubber', Waterproofing: 'Gore-Tex Equivalent' }
  },
  {
    id: '7',
    name: 'Travel Clothing Set',
    price: 3999,
    originalPrice: 4999,
    rating: 4.5,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop',
    category: 'Clothing',
    inStock: true,
    discount: 20,
    description: 'An elegant quick-dry clothing set for travelers. Includes a breathable wrinkle-free shirt and stretchable cargo pants that convert into shorts, keeping you ready for any weather.',
    features: ['Wrinkle-resistant fabric', 'Quick-dry & moisture wicking', 'UPF 50+ Sun Protection', 'Convertible pants-to-shorts', 'Hidden passport zip pocket'],
    specs: { Material: 'Nylon Spandex Blend', Fit: 'Regular Stretch', Washable: 'Machine washable', Color: 'Charcoal Grey' }
  },
  {
    id: '8',
    name: 'Premium Water Bottle',
    price: 1999,
    originalPrice: 2499,
    rating: 4.7,
    reviews: 412,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop',
    category: 'Water Bottles',
    inStock: true,
    discount: 20,
    description: 'Double-walled vacuum insulated stainless steel bottle that keeps your drinks cold for 24 hours or hot for 12 hours. Featuring a leakproof straw lid and a durable powder coat finish.',
    features: ['Vacuum insulation', 'Food-grade 18/8 Stainless Steel', 'Leakproof straw lid', 'Sweat-free powder coating', 'BPA & Toxin-free'],
    specs: { Capacity: '750 ml', Weight: '360g', Material: '18/8 Stainless Steel', Temperature: '24h Cold / 12h Hot' }
  },
  {
    id: '9',
    name: 'Camping Stove',
    price: 2999,
    originalPrice: 3999,
    rating: 4.6,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=600&h=600&fit=crop',
    category: 'Camping',
    inStock: false,
    discount: 25,
    description: 'A compact and windproof outdoor gas stove. Folds down to fit inside a pocket, yet delivers high thermal efficiency with built-in piezo electric ignition.',
    features: ['Wind-resistant design', 'Foldable pot supports', 'Piezo electric ignition', 'Adjustable flame control valve', 'Includes carrying case'],
    specs: { FuelType: 'Butane/Propane Mix', Power: '3000W', Weight: '120g', Material: 'Stainless Steel + Brass' }
  },
  {
    id: '10',
    name: 'Hiking Backpack',
    price: 8999,
    originalPrice: 10999,
    rating: 4.9,
    reviews: 267,
    image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=600&h=600&fit=crop',
    category: 'Backpacks',
    inStock: true,
    discount: 18,
    description: 'Designed for multi-day treks. Features an internal frame, customizable torso length, and a suspension system that transfers weight to your hips, relieving shoulder pressure.',
    features: ['Adjustable suspension frame', 'Integrated rain cover', 'Hydration bladder sleeve', 'Trekking pole attachments', 'Sleeping bag bottom compartment'],
    specs: { Capacity: '60 Liters', Weight: '1.75 kg', Material: '600D Ripstop Polyester', Dimensions: '72 x 34 x 24 cm' }
  },
  {
    id: '11',
    name: 'Ergonomic Travel Neck Pillow',
    price: 799,
    originalPrice: 1199,
    rating: 4.5,
    reviews: 523,
    image: 'https://images.unsplash.com/photo-1520038410233-7141be7e6f97?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 33,
    description: 'Crafted with premium high-density memory foam, this neck pillow provides 360-degree support to your head and cervical spine, helping you sleep soundly on long-haul flights.',
    features: ['Pure Memory Foam core', 'Magnetic buckle adjustment', 'Washable velvet cover', 'Ergonomic hump design', 'Includes travel compression pouch'],
    specs: { Filling: 'High Density Memory Foam', Weight: '290g', CoverMaterial: 'Soft Velvet', PackSize: '15 x 15 cm' }
  },
  {
    id: '12',
    name: 'Universal World Travel Adapter',
    price: 999,
    originalPrice: 1499,
    rating: 4.7,
    reviews: 681,
    image: 'https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=600&h=600&fit=crop',
    category: 'Electronics',
    inStock: true,
    discount: 33,
    description: 'An all-in-one charging solution compatible in over 150 countries (US, EU, UK, AU plugs). Features 4 USB ports and 1 Type-C fast charging port to charge multiple devices at once safely.',
    features: ['US/EU/UK/AUS sliders', '4 USB + 1 Type-C ports', 'Smart charging IC', 'Dual safety fuses', 'Fire-retardant PC shell'],
    specs: { InputVoltage: '100-250V AC', Output: '5V DC, max 5.6A total', Fuses: '8A Max', Certification: 'CE, FCC, RoHS' }
  },
  {
    id: '13',
    name: 'Hanging Toiletries Travel Organizer',
    price: 649,
    originalPrice: 899,
    rating: 4.6,
    reviews: 312,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 27,
    description: 'Keep your personal cosmetics and hygiene essentials neat and accessible. Hang it on any bathroom door or hook to save space and view all your items immediately.',
    features: ['Heavy-duty hanging hook', 'Water-resistant compartments', 'Elastic brush holders', 'Breathable mesh pockets', 'Compact fold-up shape'],
    specs: { FoldedDimensions: '24 x 18 x 9 cm', UnfoldedLength: '46 cm', Material: 'Waterproof Polyester', Compartments: '4 main zip sections' }
  },
  {
    id: '14',
    name: 'Compression Packing Cubes (6 Set)',
    price: 899,
    originalPrice: 1299,
    rating: 4.8,
    reviews: 492,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 30,
    description: 'Save up to 40% space in your suitcase. This set of 6 ripstop nylon packing cubes compress your clothes effortlessly while keeping them organized and wrinkle-free.',
    features: ['Double zip compression system', 'Ripstop ultralight fabric', 'Mesh windows for visibility', 'Water-resistant material', 'Includes shoe & laundry bags'],
    specs: { Quantity: '6 Cubes', Sizes: 'L, M, S, XS, Shoe, Laundry', Material: '210D Ripstop Nylon', Weight: '280g total' }
  },
  {
    id: '15',
    name: 'Digital Hanging Luggage Scale',
    price: 499,
    originalPrice: 799,
    rating: 4.4,
    reviews: 231,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&h=600&fit=crop',
    category: 'Electronics',
    inStock: true,
    discount: 37,
    description: 'Avoid excess baggage fees. Simply hook your suitcase, lift, and read the exact weight on the backlit LCD display within seconds. Highly precise sensor technology.',
    features: ['Backlit LCD screen', 'Up to 50kg capacity', 'Data lock & tare functions', 'Overload & low-battery indicators', 'Compact ergonomic handle'],
    specs: { MaxCapacity: '50 kg / 110 lbs', Accuracy: '50g', Battery: '1x CR2032 (included)', Units: 'kg, lb, oz, g' }
  },
  {
    id: '16',
    name: 'Quick-Dry Microfiber Travel Towel',
    price: 399,
    originalPrice: 599,
    rating: 4.7,
    reviews: 712,
    image: 'https://images.unsplash.com/photo-1616627561950-9f746e330187?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 33,
    description: 'Super absorbent microfiber towel that dries 3x faster than normal cotton. Highly packable, anti-odor, and includes a mesh carry bag, making it perfect for hostel stays and camping.',
    features: ['Absorbs 4x its weight in water', 'Antibacterial anti-odor weave', 'Extremely lightweight', 'Snap loop for hanging', 'Compact mesh zipper bag'],
    specs: { Dimensions: '140 x 70 cm (Large)', Weight: '110g', Material: '85% Polyester / 15% Nylon', DryTime: 'approx 20 mins' }
  },
  {
    id: '17',
    name: '3D Sleep Eye Mask & Earplugs Set',
    price: 299,
    originalPrice: 499,
    rating: 4.3,
    reviews: 145,
    image: 'https://images.unsplash.com/photo-1517423568366-8b83523034fd?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 40,
    description: 'Block out light and noise completely. Designed with contoured 3D eye cavities, this mask prevents pressure on your eyelids and eyelashes while memory foam earplugs provide total peace.',
    features: ['Contoured 3D eye spacing', 'Zero eye pressure', 'Adjustable Velcro strap', 'High noise reduction earplugs', 'Soft memory foam fabric'],
    specs: { Material: 'Lycra + Memory Foam', Weight: '35g', NoiseReduction: 'SNR 32dB (earplugs)', StrapSize: 'Adjustable' }
  },
  {
    id: '18',
    name: 'Foldable Travel Duffel Bag 30L',
    price: 599,
    originalPrice: 799,
    rating: 4.5,
    reviews: 345,
    image: 'https://images.unsplash.com/photo-1581553680321-4fffae59fccd?w=500&h=500&fit=crop',
    category: 'Luggage',
    inStock: true,
    discount: 25,
    description: 'A backup bag for souvenirs. This lightweight 30-liter duffel folds down into a pocket-sized pouch, and features a trolley sleeve to slide easily over your suitcase handle.',
    features: ['Folds into its own pocket', 'Suitcase handle trolley sleeve', 'Tear-resistant nylon fabric', 'Spacious 30L compartment', 'Dual grab handles & shoulder strap'],
    specs: { Capacity: '30 Liters', FoldedSize: '18 x 15 x 3 cm', UnfoldedSize: '45 x 32 x 16 cm', Material: 'Nylon' }
  },
  {
    id: '19',
    name: 'Waterproof Rain Backpack Cover',
    price: 349,
    originalPrice: 499,
    rating: 4.6,
    reviews: 198,
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&h=600&fit=crop',
    category: 'Backpacks',
    inStock: true,
    discount: 30,
    description: 'Protect your gear from sudden downpours. This elasticized, waterproof cover fits backpacks from 30L to 45L and features a cross buckle strap to prevent slipping off.',
    features: ['Waterproof PU coating (3000mm)', 'Elastic edge fitting', 'Cross buckle retention strap', 'Includes storage bag', 'High reflectivity logo'],
    specs: { FitsBackpacks: '30L - 45L', Material: '190T Waterproof Nylon', Weight: '60g', Coating: 'Polyurethane' }
  },
  {
    id: '20',
    name: 'RFID Blocking Leather Travel Wallet',
    price: 899,
    originalPrice: 1199,
    rating: 4.7,
    reviews: 289,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 25,
    description: 'Keep your passport, cash, cards, and boarding passes in one secure place. Features advanced RFID blocking technology to shield your digital credit card details from theft.',
    features: ['RFID Blocking lining', 'Genuine textured leather', 'Passport sleeve + 6 card slots', 'Boarding pass holder compartment', 'Zip coin pocket'],
    specs: { Dimensions: '14 x 10 x 1.5 cm', Material: 'PU Leather', Technology: 'RFID Shielding 13.56 MHz', Compartments: '9 total pockets' }
  },
  {
    id: '21',
    name: 'Pocket Size Travel First Aid Kit',
    price: 399,
    originalPrice: 499,
    rating: 4.8,
    reviews: 167,
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 20,
    description: 'Safety first. A compact, lightweight zipper pouch packed with essential medical supplies including bandages, antiseptic wipes, scissors, and medical tape for quick emergencies.',
    features: ['EVA hard case pouch', 'Compact travel dimensions', 'Fully stocked with basic supplies', 'Mesh layout interior organizer', 'Handy belt loop/clip'],
    specs: { TotalPieces: '45 medical items', Dimensions: '13 x 9 x 4 cm', Weight: '140g', CaseMaterial: 'EVA Hardshell' }
  },
  {
    id: '22',
    name: 'Travel-Sized Steam Iron',
    price: 1499,
    originalPrice: 1999,
    rating: 4.4,
    reviews: 154,
    image: 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=600&h=600&fit=crop',
    category: 'Clothing',
    inStock: true,
    discount: 25,
    description: 'Get rid of travel wrinkles instantly. This mini steam iron features dual voltage compatibility and a folding handle, taking up minimal space in your suitcase.',
    features: ['Dual voltage (120V / 240V)', 'Foldable handle mechanism', 'Rapid steam output', 'Non-stick soleplate', 'Water cup included'],
    specs: { Power: '800W', Weight: '480g', WaterCapacity: '50ml', Dimensions: '16 x 8 x 10 cm' }
  },
  {
    id: '23',
    name: 'Ultra-Slim 10000mAh Power Bank',
    price: 1299,
    originalPrice: 1799,
    rating: 4.6,
    reviews: 876,
    image: 'https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?w=600&h=600&fit=crop',
    category: 'Electronics',
    inStock: true,
    discount: 27,
    description: 'Keep your smartphone charged all day. This slim, lightweight power bank features fast charging technology and dual output ports to power two devices simultaneously.',
    features: ['Dual USB outputs', '12W Fast Charge', 'Intelligent power protection', 'Slim 14mm profile', 'LED battery indicators'],
    specs: { Capacity: '10000 mAh', Weight: '180g', InputPort: 'Type-C & Micro USB', OutputPorts: '2x USB-A' }
  },
  {
    id: '24',
    name: 'Graduated Flight Compression Socks',
    price: 499,
    originalPrice: 799,
    rating: 4.5,
    reviews: 213,
    image: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?w=600&h=600&fit=crop',
    category: 'Clothing',
    inStock: true,
    discount: 37,
    description: 'Prevent swollen ankles and deep vein thrombosis (DVT) during long flights. These socks provide graduated compression from ankle to calf to boost blood circulation.',
    features: ['Graduated compression 15-20 mmHg', 'Breathable moisture-wicking knit', 'Reinforced toe & heel padding', 'Elastic comfort top band', 'Unisex design'],
    specs: { Material: 'Nylon Spandex Blend', CompressionLevel: '15-20 mmHg', Washable: 'Hand/Machine wash', Style: 'Knee High' }
  },
  {
    id: '25',
    name: 'Collapsible Silicone Travel Cup',
    price: 249,
    originalPrice: 399,
    rating: 4.2,
    reviews: 95,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&h=600&fit=crop',
    category: 'Water Bottles',
    inStock: true,
    discount: 37,
    description: 'Eco-friendly and pocketable. This silicone cup collapses flat to save space, features a heat-insulating plastic sleeve, and includes a leakproof lid for hot drinks.',
    features: ['Collapses flat (1.8cm high)', 'Heat-resistant sleeve ring', 'Leakproof sealing lid', 'Food-grade silicone', 'Metal hanging hook'],
    specs: { Capacity: '350 ml', Material: 'FDA Approved Silicone', Temperature: '-50°C to 200°C', Weight: '130g' }
  },
  {
    id: '26',
    name: 'Portable Travel Clothesline',
    price: 299,
    originalPrice: 499,
    rating: 4.3,
    reviews: 78,
    image: 'https://images.unsplash.com/photo-1520697830682-bbb6e85e2b0b?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 40,
    description: 'Dry your clothes anywhere. An elastic, braided clothesline that doesn\'t require clothespins. Features suction cups and steel hooks on ends to attach to hotel walls or trees.',
    features: ['No-clothespin braided design', 'Elastic stretchable line', 'Steel hooks + suction cups', 'Compact and lightweight', 'Rust-resistant materials'],
    specs: { Length: '1.8m (stretches to 3.6m)', Weight: '80g', Material: 'Elastic cord + PVC hooks' }
  },
  {
    id: '27',
    name: 'Travel Mini Capsule Umbrella',
    price: 499,
    originalPrice: 799,
    rating: 4.4,
    reviews: 114,
    image: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 37,
    description: 'An ultra-compact capsule umbrella. Fits in the palm of your hand when folded, yet opens to a full-sized waterproof and UV-blocking canopy.',
    features: ['Fits inside waterproof capsule', 'UV blocking coating', 'Alloy anti-wind structure', 'Pocketsized dimensions', 'Ultralightweight design'],
    specs: { FoldedLength: '17 cm', CanopyDiameter: '90 cm', Weight: '200g', RibsCount: '6 Ribs' }
  },
  {
    id: '28',
    name: 'Noise Cancelling Travel Earbuds',
    price: 2499,
    originalPrice: 3499,
    rating: 4.7,
    reviews: 320,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop',
    category: 'Electronics',
    inStock: true,
    discount: 28,
    description: 'Block engine rumble and traffic noise. These wireless earbuds feature hybrid Active Noise Cancellation (ANC), deep bass, and comfortable silicone ear tips for long transits.',
    features: ['Active Noise Cancellation (ANC)', '30 Hours battery life with case', 'Fast charge Type-C', 'Touch controls & Mic', 'Sweatproof IPX5 design'],
    specs: { Connectivity: 'Bluetooth 5.3', ANCLevel: '28dB', Battery: '6h Buds / 30h total', Drivers: '10mm Dynamic' }
  },
  {
    id: '29',
    name: 'Portable UV Toothbrush Sanitizer',
    price: 799,
    originalPrice: 1199,
    rating: 4.5,
    reviews: 86,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=600&fit=crop',
    category: 'Accessories',
    inStock: true,
    discount: 33,
    description: 'Sanitize your toothbrush on the go. This compact travel case uses UV-C light to kill 99.9% of bacteria and germs on your toothbrush head in just 5 minutes.',
    features: ['99.9% germ eradication', 'UV-C LED technology', '5-minute auto shut off', 'USB rechargeable battery', 'Fits manual & electric heads'],
    specs: { LightType: 'UV-C LED', Battery: 'Rechargeable, 30 days use', Weight: '65g', Dimensions: '7.5 x 6.0 x 3.0 cm' }
  },
  {
    id: '30',
    name: 'Ultralight Inflatable Sleeping Pad',
    price: 2199,
    originalPrice: 2999,
    rating: 4.8,
    reviews: 112,
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=600&fit=crop',
    category: 'Camping',
    inStock: true,
    discount: 26,
    description: 'Get a good night\'s sleep anywhere outdoors. This inflatable camping pad has a unique honeycomb air cell design to support your pressure points, and packs down to the size of a water bottle.',
    features: ['Honeycomb air cell support', 'Built-in foot pump inflator', 'Ripstop heavy duty TPU', 'Thermal R-Value 2.2 insulation', 'Repairs kit included'],
    specs: { InflatedDimensions: '190 x 60 x 5 cm', PackedSize: '22 x 9 cm', Material: '40D Nylon TPU', Weight: '490g' }
  }
];
